### ISSUE TITLE
deomposition for single-channel intra-muscular EMG

### ISSUE THREAD

**Issue by AthiemoneZero** [carmenalab/emgdecomp#5]
Hi, very grateful for the great work you paid on this package!

I recently recorded muscle activity in mouse using single-channel paired wires and I am a newer to analyze EMG raw data. I'm wondering if this package can be applied to my data?

**Comment by pbotros** [comment]
@AthiemoneZero theoretically it can! Though I'll mention that it's currently tailored towards and has only been validated with surface EMG recordings. The methods follow from Negro et al, 2016, with some tweaks (DOI: 10.1088/1741-2560/13/2/026027), so I'd recommend becoming acquainted with that study first. An alternative possible solution here is using methodology similar to Marshall et al 2022 (https://doi.org/10.1038/s41593-022-01165-8) but we've never tried that ourselves.

**Comment by AthiemoneZero** [comment]
Thanks for your reply. This sounds really convincing. I find most decomposition tools follow from Negro et al, 2016, but I guess it might cause problem when it is apllied to single-channel intra-muscular EMG from mouse. As the experimental data on Negro et al, 2016 mainly came from surface EMG recording array with multi-electrodes. The methodology from Marshall et al 2022, again, is really convincing. But still here I am not sure if it will work for me. 

I will try both  of these, if possible, I think there might be some feedback and I will give back to you.
